spring.datasource.url=jdbc:postgresql://localhost:5432/${DOCKER_DB_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DOCKER_DB_USER}
spring.datasource.password=${DOCKER_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update